# Generated by nixos-generate-config on xiuhcoatl.
# Do not edit this file manually — regenerate it with:
#
#   nixos-generate-config --show-hardware-config > hosts/xiuhcoatl/hardware-configuration.nix
#
{ ... }:
{
  # placeholder — replace with actual output from nixos-generate-config
}
